# Generated by Django 4.1.5 on 2023-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('result', models.TextField()),
                ('empty_views', models.CharField(max_length=255)),
                ('command', models.CharField(max_length=255)),
            ],
        ),
    ]
