# Generated by Django 4.1.5 on 2023-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convertor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_title', models.JSONField(blank=True, default=dict)),
                ('download_help', models.TextField()),
                ('download_table_title', models.CharField(max_length=255)),
                ('result_table_title', models.CharField(max_length=255)),
                ('editor', models.JSONField(blank=True, default=dict)),
                ('download_button_title', models.CharField(max_length=255)),
                ('view_text_result', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_cells_title', models.CharField(max_length=255)),
                ('result_cells_title', models.CharField(max_length=255)),
                ('convertor_commands', models.JSONField(blank=True, default=list)),
                ('view_empty_cells', models.JSONField(blank=True, default=dict)),
                ('apply_button_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorEditor_ViewEmptyCells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('views', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorFormatTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.TextField()),
                ('result_format', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorViewTextResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_format_title', models.CharField(max_length=255)),
                ('settings', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorViewTextResult_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('text', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('status_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=255)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('app_description', models.TextField()),
                ('formats_title', models.CharField(max_length=255)),
                ('formats_help', models.TextField()),
                ('convertation_formats', models.JSONField(blank=True, default=list)),
                ('data_formats', models.JSONField(blank=True, default=list)),
                ('confidentiality_title', models.CharField(max_length=255)),
                ('confidentiality_text', models.TextField()),
                ('tagline', models.TextField()),
                ('communities', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageDataFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPageFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.TextField()),
                ('result_format', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
