# Generated by Django 4.1.5 on 2023-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.TextField()),
                ('result_format', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('app_description', models.TextField()),
                ('formats_title', models.CharField(max_length=255)),
                ('formats_help', models.TextField()),
                ('convertation_formats', models.JSONField(default=list)),
                ('data_formats', models.JSONField(default=list)),
                ('confidentiality_title', models.CharField(max_length=255)),
                ('confidentiality_text', models.TextField()),
                ('tagline', models.TextField()),
                ('communities', models.JSONField(default=list)),
            ],
        ),
        migrations.RenameModel(
            old_name='DefaultExample',
            new_name='DataFormats',
        ),
        migrations.DeleteModel(
            name='Excel',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
