# Generated by Django 4.1.5 on 2023-05-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_ownjson_communities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnJson',
            new_name='MainPage',
        ),
        migrations.RenameModel(
            old_name='DataFormats',
            new_name='MainPageDataFormats',
        ),
        migrations.RenameModel(
            old_name='Formats',
            new_name='MainPageFormats',
        ),
    ]
