# Generated by Django 4.1.5 on 2023-05-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_ownjson_mainpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convertor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_title', models.JSONField(blank=True, default=dict)),
                ('download_help', models.TextField()),
                ('download_table_title', models.CharField(max_length=255)),
                ('result_table_title', models.CharField(max_length=255)),
                ('editor', models.JSONField(blank=True, default=dict)),
                ('download_buttom_title', models.CharField(max_length=255)),
                ('view_text_result', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_cells_title', models.CharField(max_length=255)),
                ('result_cells_title', models.CharField(max_length=255)),
                ('convertor_commands', models.JSONField(blank=True, default=list)),
                ('view_empty_cells', models.JSONField(blank=True, default=list)),
                ('apply_buttom_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorEditor_ViewEmptyCells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('views', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorFormatTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_format', models.TextField()),
                ('result_format', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorViewTextResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_format_title', models.TextField()),
                ('settings', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertorViewTextResult_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('text', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('status_text', models.TextField()),
            ],
        ),
    ]
