# Generated by Django 4.1.5 on 2023-05-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_convertor_convertoreditor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertor',
            old_name='download_buttom_title',
            new_name='download_button_title',
        ),
        migrations.RenameField(
            model_name='convertoreditor',
            old_name='apply_buttom_title',
            new_name='apply_button_title',
        ),
        migrations.AlterField(
            model_name='convertorviewtextresult',
            name='result_format_title',
            field=models.CharField(max_length=255),
        ),
    ]
