# Generated by Django 4.1.5 on 2023-05-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_download_buttom_title_convertor_download_button_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertoreditor',
            name='view_empty_cells',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
